# Generated by Django 3.2.5 on 2021-07-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=16)),
                ('school', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=5)),
                ('status', models.IntegerField(max_length=2)),
                ('regist_data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
