# Generated by Django 3.2.5 on 2021-07-20 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicname', models.CharField(max_length=64)),
                ('authorname', models.CharField(max_length=64)),
                ('music_href', models.CharField(max_length=255)),
                ('click', models.IntegerField()),
                ('img_href', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
                ('comments', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField()),
                ('add_data', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.user')),
            ],
        ),
    ]
