# Generated by Django 3.2.5 on 2021-07-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20210720_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
