# Generated by Django 3.2.5 on 2021-07-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lable',
            field=models.CharField(default='', max_length=255),
        ),
    ]
