# Generated by Django 3.2.5 on 2021-07-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_user_lable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64)),
                ('friendid', models.CharField(max_length=64)),
            ],
        ),
    ]
